### ISSUE TITLE
Hardcoded?

### ISSUE THREAD

**Issue by dinism** [sbourget/moodle-block_links#3]
I'm Pt-PT translator
Is this string hardcoded to english?
$string['all'] = 'All'
![imagem](https://user-images.githubusercontent.com/14828021/118995443-0fae5300-b97f-11eb-86fc-d5fdca9bb744.png)

I think a space between would be good.
![imagem](https://user-images.githubusercontent.com/14828021/118995643-3bc9d400-b97f-11eb-8f64-af767e079f62.png)
Thanks for the plugin.

**Comment by sbourget** [comment]
I've pushed a set of fixes to github.  Please try testing with the latest master release.   If it works for you I'll publish a new version to the plugins database on Moodle.org

**Comment by dinism** [comment]
WORKING!!
